/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/compressed/stuc_draco_02.glb --output=src/components/3D/models/Structure.jsx 
*/


import React from 'react'
import { useGLTF } from '@react-three/drei'

const BASE = import.meta.env.BASE_URL

export function Structure(props) {
  const { nodes, materials } = useGLTF(`${BASE}models/compressed/stuc_draco_02.glb`)
  return (
    <group {...props} dispose={null}>
      <group position={[1.581, 14.055, 4.882]}>
        <group position={[-1.581, -14.055, -4.882]}>
          <mesh geometry={nodes.Plane_1.geometry} material={materials['RS Toon']} position={[0, -1.708, 0]} />
          <mesh geometry={nodes.Cube7.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.bottom.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane8.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane9.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane11.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane12.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane14.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane_2.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane2.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane3.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane5.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane6.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane10.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane7.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane4.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane1_1.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane13.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane_3.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane_4.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane_5.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane1_2.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.Plane2_1.geometry} material={materials['RS Toon']} />
          <mesh geometry={nodes.ground.geometry} material={materials['RS Toon']} position={[-19.709, 0, 67.888]} />
          <mesh geometry={nodes['Cube-Cube1'].geometry} material={materials['RS Toon']} position={[-8.514, -3.199, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(`${BASE}models/compressed/stuc_draco_02.glb`)
export default Structure